# Generated by Django 5.2 on 2025-07-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0013_alter_publicappointment_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_records', to='clinic.patient')),
            ],
            options={
                'verbose_name': 'Lab Test Record',
                'verbose_name_plural': 'Lab Test Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labtest.labtestrecord')),
            ],
            options={
                'verbose_name': 'Lab Test Result',
                'verbose_name_plural': 'Lab Test Results',
            },
        ),
    ]
