# Generated by Django 5.2 on 2025-07-05 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
