# Generated by Django 5.2 on 2025-07-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_category_options_product_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='issued_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.product')),
            ],
        ),
    ]
