# Generated by Django 5.2 on 2025-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_product_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together={('product', 'batch_number')},
        ),
    ]
