# Generated by Django 5.2 on 2025-05-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
