# Generated by Django 5.2 on 2025-07-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_doctor_email_alter_doctor_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicappointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_appointments', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='publicappointment',
            name='token',
            field=models.CharField(default='8703B15718', max_length=10, unique=True),
        ),
    ]
