# Generated by Django 5.2 on 2025-07-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_publicappointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicappointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='publicappointment',
            name='token',
            field=models.CharField(default='092CA6CA84', max_length=10, unique=True),
        ),
    ]
