# Generated by Django 5.2 on 2025-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_contactmessage_is_read_alter_publicappointment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicappointment',
            name='token',
            field=models.CharField(default='6451B1BA0F', max_length=10, unique=True),
        ),
    ]
